# Generated by Django 3.1.5 on 2021-01-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('AS', 'Arrays and Strings'), ('LL', 'Linked Lists'), ('SQ', 'Stacks and Queues'), ('TG', 'Trees and Graphs'), ('RD', 'Recursion and Dynamic Programming'), ('SS', 'Sorting and Searching')], help_text='Question category', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], help_text='Question difficulty', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='codingQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('N', 'Not attempted'), ('P', 'Practicing'), ('C', 'Completed')], default='N', help_text='Question status', max_length=1)),
                ('last_studied', models.DateTimeField(verbose_name='Last Studied')),
                ('upcoming_reminder', models.DateTimeField(verbose_name='Upcoming Reminder')),
                ('question_text', models.TextField(help_text='Enter a description of the question', max_length=1000)),
                ('solution_stategy', models.TextField(help_text='Enter the strategy for solving the problem ', max_length=1000)),
                ('category', models.ForeignKey(help_text='Select a category for this question', on_delete=django.db.models.deletion.RESTRICT, to='codingQs.category')),
                ('difficulty', models.ForeignKey(help_text='Select a difficulty for this question', on_delete=django.db.models.deletion.RESTRICT, to='codingQs.difficulty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_attempted', models.DateTimeField(verbose_name='Time Attempted')),
                ('status', models.CharField(choices=[('S', 'Solved'), ('U', 'Unsolved')], default='U', help_text='Indicate whether attempt was successful', max_length=1)),
                ('time_to_solve', models.DurationField(blank=True)),
                ('notes', models.TextField(help_text='Enter what you learned from this attempt', max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='codingQs.codingq')),
            ],
            options={
                'ordering': ['-time_attempted'],
            },
        ),
    ]
