# Generated by Django 3.1.5 on 2021-01-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingQs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='codingq',
            options={'ordering': ['name'], 'verbose_name_plural': 'Coding Questions'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'difficulties'},
        ),
        migrations.AddField(
            model_name='codingq',
            name='solution_code',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
