# Generated by Django 3.1.5 on 2021-01-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingQs', '0002_auto_20210112_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingq',
            name='solution_code',
            field=models.ImageField(blank=True, upload_to='solutionPNGs'),
        ),
    ]
