# Generated by Django 3.1.5 on 2021-01-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingQs', '0003_auto_20210112_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingq',
            name='last_studied',
            field=models.DateTimeField(blank=True, verbose_name='Last Studied'),
        ),
        migrations.AlterField(
            model_name='codingq',
            name='upcoming_reminder',
            field=models.DateTimeField(blank=True, verbose_name='Upcoming Reminder'),
        ),
    ]
