# Generated by Django 3.1.5 on 2021-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingQs', '0004_auto_20210113_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingq',
            name='codingQ_ide',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingq',
            name='last_studied',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Studied'),
        ),
        migrations.AlterField(
            model_name='codingq',
            name='solution_code',
            field=models.ImageField(blank=True, null=True, upload_to='solutionPNGs'),
        ),
        migrations.AlterField(
            model_name='codingq',
            name='upcoming_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Upcoming Reminder'),
        ),
    ]
